#ifndef MAIN_UI_H
#define MAIN_UI_H

const char *main_ui_xml = 
"<!-- main.ui -->\n"
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<interface>\n"
"    <requires lib=\"gtk+\" version=\"2.16\" />\n"
"    <object class=\"GtkWindow\" id=\"main_window\">\n"
"        <property name=\"title\">L:A_N:application_ID:gambatte_PC:N_O:URL_DM:PZ</property>\n"
"        <property name=\"resizable\">True</property>\n"
"        <child>\n"
"            <object class=\"GtkVBox\" id=\"main_vbox\">\n"
"                <property name=\"spacing\">5</property>\n"
"                <child>\n"
"                    <object class=\"GtkHBox\" id=\"options_box\">\n"
"                        <property name=\"homogeneous\">True</property>\n"
"                        <property name=\"spacing\">2</property>\n"
"                        <child>\n"
"                            <object class=\"GtkButton\" id=\"open_btn\">\n"
"                                <property name=\"label\">Open</property>\n"
"                                <signal name=\"clicked\" handler=\"on_open\" />\n"
"                            </object>\n"
"                        </child>\n"
"                        <child>\n"
"                            <object class=\"GtkButton\" id=\"load_btn\">\n"
"                                <property name=\"label\">Load</property>\n"
"                            </object>\n"
"                        </child>\n"
"                        <child>\n"
"                            <object class=\"GtkButton\" id=\"save_btn\">\n"
"                                <property name=\"label\">Save</property>\n"
"                            </object>\n"
"                        </child>                        \n"
"                        <child>\n"
"                            <object class=\"GtkToggleButton\" id=\"gtk_toggle\">\n"
"                                <property name=\"label\">GTK</property>\n"
"                                <property name=\"active\">True</property>\n"
"                            </object>\n"
"                        </child>\n"
"                        <child>\n"
"                            <object class=\"GtkToggleButton\" id=\"fbink_toggle\">\n"
"                                <property name=\"label\">FBInk</property>\n"
"                            </object>\n"
"                        </child>\n"
"                        <child>\n"
"                            <object class=\"GtkToggleButton\" id=\"style_toggle\">\n"
"                                <property name=\"label\">Light</property>\n"
"                            </object>\n"
"                        </child>                        \n"
"                        <child>\n"
"                            <object class=\"GtkButton\" id=\"refresh_button\">\n"
"                                <property name=\"label\">Refresh</property>\n"
"                                <signal name=\"clicked\" handler=\"on_refresh\" />\n"
"                            </object>\n"
"                        </child>                        \n"
"                        <child>\n"
"                            <object class=\"GtkButton\" id=\"quit_button\">\n"
"                                <property name=\"label\">Quit</property>\n"
"                                <signal name=\"clicked\" handler=\"on_quit\" />\n"
"                            </object>\n"
"                        </child>\n"
"                    </object>\n"
"                    <packing>\n"
"                        <property name=\"expand\">False</property>\n"
"                        <property name=\"fill\">False</property>\n"
"                        <property name=\"padding\">0</property>\n"
"                    </packing>\n"
"                </child>\n"
"                <child>\n"
"                    <object class=\"GtkHBox\" id=\"center_hbox\">\n"
"                        <child>\n"
"                            <object class=\"GtkLabel\" id=\"left_spacer\" />\n"
"                        </child>\n"
"                        <child>\n"
"                            <object class=\"GtkVBox\" id=\"center_vbox\">\n"
"                                <child>\n"
"                                    <object class=\"GtkLabel\" id=\"top_spacer\" />\n"
"                                </child>\n"
"                                <child>\n"
"                                    <object class=\"GtkEventBox\" id=\"drawing_area_container\">\n"
"                                        <child>\n"
"                                            <object class=\"GtkHBox\" id=\"center_hbox2\">\n"
"                                                <child>\n"
"                                                    <object class=\"GtkLabel\" id=\"left_spacer2\" />\n"
"                                                </child>\n"
"                                                <child>\n"
"                                                    <object class=\"GtkVBox\" id=\"center2_vbox\">\n"
"                                                        <child>\n"
"                                                            <object class=\"GtkLabel\"\n"
"                                                                id=\"top_spacer2\" />\n"
"                                                        </child>\n"
"                                                        <child>\n"
"                                                            <object class=\"GtkDrawingArea\"\n"
"                                                                id=\"drawing_area\" />\n"
"                                                            <packing>\n"
"                                                                <property name=\"expand\">False</property>\n"
"                                                                <property name=\"fill\">False</property>\n"
"                                                            </packing>\n"
"                                                        </child>\n"
"                                                        <child>\n"
"                                                            <object class=\"GtkLabel\"\n"
"                                                                id=\"bottom_spacer2\" />\n"
"                                                        </child>\n"
"                                                    </object>\n"
"                                                    <packing>\n"
"                                                        <property name=\"expand\">False</property>\n"
"                                                        <property name=\"fill\">False</property>\n"
"                                                    </packing>\n"
"                                                </child>\n"
"                                                <child>\n"
"                                                    <object class=\"GtkLabel\" id=\"right_spacer2\" />\n"
"                                                </child>\n"
"                                            </object>\n"
"                                        </child>\n"
"                                    </object>\n"
"                                    <packing>\n"
"                                        <property name=\"expand\">False</property>\n"
"                                        <property name=\"fill\">False</property>\n"
"                                    </packing>\n"
"                                </child>\n"
"                                <child>\n"
"                                    <object class=\"GtkLabel\" id=\"bottom_spacer\" />\n"
"                                </child>\n"
"                            </object>\n"
"                            <packing>\n"
"                                <property name=\"expand\">False</property>\n"
"                                <property name=\"fill\">False</property>\n"
"                            </packing>\n"
"                        </child>\n"
"                        <child>\n"
"                            <object class=\"GtkLabel\" id=\"right_spacer\" />\n"
"                        </child>\n"
"                    </object>\n"
"                    <packing>\n"
"                        <property name=\"expand\">False</property>\n"
"                        <property name=\"fill\">False</property>\n"
"                    </packing>\n"
"                </child>\n"
"                <child>\n"
"                    <object class=\"GtkDrawingArea\" id=\"joystick_area\" />\n"
"                </child>\n"
"            </object>\n"
"        </child>\n"
"    </object>\n"
;

#endif /* MAIN_UI_H */
